# Site settings
title: Zach Maillard
email: sagebrushgis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description Goes Here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zmaillard.github.io"
twitter_username: sagebrushgis
github_username:  zmaillard

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude:
  - "bower_components"
  - "bower.json"
