# Site settings
title: Zach Maillard
email: sagebrushgis@gmail.com
description: >
  Musings from a software developer and a cartographer.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zmaillard.github.io"
twitter_username: sagebrushgis
github_username:  zmaillard
linkedin_username: zachmaillard

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude:
  - "vendor/bundle"
  - "Rakefile"
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - ".travis.yml"
